#!/system/bin/sh
# TCP Config module — apply the saved settings at boot.
#
# The only privileged control path is the KernelSU WebUI bridge. There is no
# TCP listener: a socket cannot establish the caller's Android identity, so an
# unauthenticated nc fallback would turn a network request into a root sysctl.
# Without a state file nothing is touched (the kernel default wins).

STATE=/data/adb/tcpcfg.state

log() { echo "tcp-config: $*"; }

# Do not source the state file. It is generated by apply.sh, but parsing only
# expected values prevents a malformed file from becoming shell code.
if [ -f "$STATE" ]; then
    ALGO=$(sed -n 's/^ALGO=//p' "$STATE" | head -n 1)
    QDISC=$(sed -n 's/^QDISC=//p' "$STATE" | head -n 1)
    case "$ALGO" in
        cubic|bbr|kerneldflt) ;;
        *) log "ERROR: invalid saved algorithm"; exit 1 ;;
    esac
    case "$QDISC" in
        fq|fq_codel|pfifo_fast) ;;
        *) log "ERROR: invalid saved qdisc"; exit 1 ;;
    esac

    if [ "$ALGO" = kerneldflt ]; then
        DFLT=$(zcat /proc/config.gz 2>/dev/null | grep -oE '^CONFIG_DEFAULT_TCP_CONG="[^"]*"' | cut -d'"' -f2)
        [ -n "$DFLT" ] || DFLT=cubic
        FINAL_ALGO=$DFLT
    else
        FINAL_ALGO=$ALGO
    fi
    if sysctl -w net.ipv4.tcp_congestion_control="$FINAL_ALGO" >/dev/null 2>&1 \
       && sysctl -w net.core.default_qdisc="$QDISC" >/dev/null 2>&1; then
        log "applied ALGO=$ALGO QDISC=$QDISC"
    else
        log "ERROR: failed to apply saved settings"
        exit 1
    fi
else
    log "no state, leaving kernel defaults"
fi

exit 0
