#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOLCHAIN_ROOT="${ACE6_TOOLCHAIN_ROOT:-$ROOT_DIR/.toolchains}"
ENV_FILE="$ROOT_DIR/.ace6-toolchain.env"
FISH_ENV_FILE="$ROOT_DIR/.ace6-toolchain.fish"

ARM_VERSION="15.2.rel1"
ARM_ARCHIVE="arm-gnu-toolchain-${ARM_VERSION}-x86_64-aarch64-none-elf.tar.xz"
ARM_URL="${ACE6_ARM_URL:-https://developer.arm.com/-/media/Files/downloads/gnu/${ARM_VERSION}/binrel/${ARM_ARCHIVE}}"

CLANG_ARCHIVE="clang-r563880c.tar.gz"
CLANG_SHA256="ee099045b1323087e0c1d3962d1d8c582fcdef45986976b82886a6177f142763"
CLANG_ORIGIN="https://github.com/GuLingguang/oneplus-sm8750-kernel-pro-build/releases/download/toolchain-AOSP-Clang-21.0.0-r563880c/${CLANG_ARCHIVE}"
CLANG_URL="${ACE6_CLANG_URL:-$CLANG_ORIGIN}"
CLANG_MIRROR="https://v4.gh-proxy.org/${CLANG_ORIGIN}"

die() {
    echo "error: $*" >&2
    exit 1
}

need_command() {
    command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

download() {
    local url="$1"
    local destination="$2"
    local partial="${destination}.part.$$"
    echo "download: $url"
    curl -fL --retry 3 --retry-all-errors --connect-timeout 15 \
        --max-time 1800 -o "$partial" "$url"
    mv -f "$partial" "$destination"
}

verify_sidecar_sha256() {
    local archive="$1"
    local sidecar="$2"
    local expected actual
    expected="$(awk '$1 ~ /^[[:xdigit:]]{64}$/ {print tolower($1); exit}' "$sidecar")"
    [[ -n "$expected" ]] || die "no SHA-256 digest found in $sidecar"
    actual="$(sha256sum "$archive" | awk '{print $1}')"
    [[ "$expected" == "$actual" ]] || die "SHA-256 mismatch for $(basename "$archive")"
    echo "verified: $(basename "$archive") ($actual)"
}

verify_fixed_sha256() {
    local archive="$1"
    local actual
    actual="$(sha256sum "$archive" | awk '{print $1}')"
    [[ "$actual" == "$CLANG_SHA256" ]] || die "AOSP Clang SHA-256 mismatch: $actual"
    echo "verified: $(basename "$archive") ($actual)"
}

(( EUID != 0 )) || die "run this script as the normal user; it invokes sudo/pacman itself"

for command_name in curl tar sha256sum awk pacman paru sudo python3 fish; do
    need_command "$command_name"
done

mkdir -p "$TOOLCHAIN_ROOT"

echo "== install CachyOS build dependencies =="
sudo -E pacman -S --needed \
    base-devel cmake ninja git patch zip zstd bc flex bison \
    openssl ncurses libelf pahole python ccache llvm clang lld android-tools

echo "== install Android NDK from AUR =="
echo "The default provider should be android-ndk (r29)."
paru -S --needed android-ndk

echo "== install and verify Arm GNU Toolchain ${ARM_VERSION} =="
arm_archive_path="$TOOLCHAIN_ROOT/$ARM_ARCHIVE"
arm_sidecar_path="${arm_archive_path}.sha256asc"
if [[ ! -s "$arm_archive_path" ]]; then
    download "$ARM_URL" "$arm_archive_path"
fi
if [[ ! -s "$arm_sidecar_path" ]]; then
    download "${ARM_URL}.sha256asc" "$arm_sidecar_path"
fi
verify_sidecar_sha256 "$arm_archive_path" "$arm_sidecar_path"

arm_dir="$TOOLCHAIN_ROOT/arm-gnu-toolchain-${ARM_VERSION}-x86_64-aarch64-none-elf"
if [[ ! -x "$arm_dir/bin/aarch64-none-elf-gcc" ]]; then
    tar -xJf "$arm_archive_path" -C "$TOOLCHAIN_ROOT"
fi
[[ -x "$arm_dir/bin/aarch64-none-elf-gcc" ]] || die "Arm toolchain extraction did not produce $arm_dir/bin/aarch64-none-elf-gcc"

echo "== install and verify locked AOSP Clang 21 =="
clang_archive_path="$TOOLCHAIN_ROOT/$CLANG_ARCHIVE"
if [[ ! -s "$clang_archive_path" ]]; then
    if ! download "$CLANG_URL" "$clang_archive_path"; then
        [[ "$CLANG_URL" == "$CLANG_ORIGIN" ]] || die "AOSP Clang download failed"
        echo "primary GitHub URL failed; trying the configured gh-proxy mirror" >&2
        download "$CLANG_MIRROR" "$clang_archive_path"
    fi
fi
verify_fixed_sha256 "$clang_archive_path"

clang_dir="$TOOLCHAIN_ROOT/clang-r563880c"
if [[ ! -x "$clang_dir/bin/clang" ]]; then
    mkdir -p "$clang_dir"
    tar -xzf "$clang_archive_path" -C "$clang_dir"
fi
[[ -x "$clang_dir/bin/clang" ]] || die "AOSP Clang extraction did not produce $clang_dir/bin/clang"

ndk_toolchain_file="$(pacman -Ql android-ndk 2>/dev/null | \
    awk '$2 ~ /\/build\/cmake\/android\.toolchain\.cmake$/ {print $2; exit}')"
[[ -n "$ndk_toolchain_file" ]] || die "could not locate Android NDK CMake toolchain"
ANDROID_NDK="${ndk_toolchain_file%/build/cmake/android.toolchain.cmake}"

arm_bin="$arm_dir/bin"
clang_bin="$clang_dir/bin"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-build-deps.sh
export ACE6_TOOLCHAIN_ROOT=$(printf '%q' "$TOOLCHAIN_ROOT")
export TARGET_COMPILE=aarch64-none-elf-
export ANDROID_NDK=$(printf '%q' "$ANDROID_NDK")
export PATH=$(printf '%q' "$arm_bin:$clang_bin"):\$PATH
EOF

fish_quote() {
    fish -c 'string escape -- "$argv[1]"' -- "$1"
}

cat > "$FISH_ENV_FILE" <<EOF
# Generated by scripts/setup-build-deps.sh
set -gx ACE6_TOOLCHAIN_ROOT $(fish_quote "$TOOLCHAIN_ROOT")
set -gx TARGET_COMPILE aarch64-none-elf-
set -gx ANDROID_NDK $(fish_quote "$ANDROID_NDK")
fish_add_path --global --prepend $(fish_quote "$arm_bin") $(fish_quote "$clang_bin")
EOF

export TARGET_COMPILE="aarch64-none-elf-"
export ANDROID_NDK
export PATH="$arm_bin:$clang_bin:$PATH"

echo "== verify installed toolchains =="
aarch64-none-elf-gcc --version | head -n 1
aarch64-none-elf-ld --version | head -n 1
aarch64-none-elf-objcopy --version | head -n 1
clang --version | head -n 1
command -v ld.lld
zip -v | head -n 2
test -f "$ANDROID_NDK/build/cmake/android.toolchain.cmake"

echo "== verify project lock =="
python3 "$ROOT_DIR/scripts/build.py" --verify-toolchain "$clang_archive_path"

echo
echo "setup complete"
echo "bash: source $(printf '%q' "$ENV_FILE")"
echo "fish: source $(printf '%q' "$FISH_ENV_FILE")"
echo "TARGET_COMPILE=$TARGET_COMPILE"
echo "ANDROID_NDK=$ANDROID_NDK"
